void mostrarInfoArray(int array[],int size);
int retornarTotal(int array[],int size);
void cargarListado(int array[],int size);
float promedioNotas(int array[],int size);
int retornarNumeroMenor(int array[],int size);
int retornarNumeroMayor(int array[],int size);
int retornarNumerosPares(int array[],int size);
int alumnosAprobadosDesaprobados(int array[],int size,int limiteInferior,int limiteSuperior);
int getCaracter(char * caracterAuxiliar,char mensaje[50]);
int menuNotasIngresadas(int array[],int size);
void limpiarPantalla();
void limpiarMemoria();
